### PR TITLE
fix[windows]: run method call on main thread

### LINKED ISSUE #1212: ERROR:flutter/shell/common/shell.cc(1057)] The 'com.alexmercerind/media_kit_video' channel sent a message from native to Flutter
[ERROR:flutter/shell/common/shell.cc(1057)] The 'com.alexmercerind/media_kit_video' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.

### PR DESCRIPTION
**Pull request by Predidit**
fixes #1212

This PR builds on the approach introduced in flutter/packages#5884, using PostMessage and a top-level Window Proc Delegate to marshal work onto the main thread that owns the target HWND. It resolves the long-standing warning described in issue #1212.

@alexmercerind 

I’m not deeply versed in the Win32 API, so any corrections, optimizations, or style suggestions are very welcome. Thank you for your feedback!

### CODE REVIEW

File: media_kit_video/windows/media_kit_video_plugin.cc [hunk 1]
```diff
@@ -64,42 +130,43 @@ void MediaKitVideoPlugin::HandleMethodCall(
...
-                          {
-                              flutter::EncodableValue("height"),
-                              flutter::EncodableValue(height),
-                          },
-                      }),
-                  },
-              }),
-              nullptr);
+        [this, handle = handle_value](auto id, auto width, auto height) {
+          RunOnMainThread([this, handle, id, width, height]() {
```
Comment (alexmercerind) [inline media_kit_video/windows/media_kit_video_plugin.cc:134]:
```suggestion
          RunOnMainThread([&]() {
```

File: media_kit_video/windows/media_kit_video_plugin.h [hunk 2]
```diff
@@ -31,10 +35,21 @@ class MediaKitVideoPlugin : public flutter::Plugin {
...
+  void RunOnMainThread(std::function<void()> task);
+  static LRESULT CALLBACK WindowProcDelegate(HWND hwnd, UINT message, WPARAM wParam, LPARAM lParam);
+  void ProcessMainThreadTasks();
+  
   flutter::PluginRegistrarWindows* registrar_ = nullptr;
   std::unique_ptr<flutter::MethodChannel<flutter::EncodableValue>> channel_ =
       nullptr;
   std::unique_ptr<VideoOutputManager> video_output_manager_ = nullptr;
+  
+  static const UINT WM_MAIN_THREAD_TASK = WM_USER + 1001;
```
Comment (alexmercerind) [inline media_kit_video/windows/media_kit_video_plugin.h:47]: The project declares constants like this, top most just below `private:`:

https://github.com/media-kit/media-kit/blob/c7a9dd70ce955e63a24c4800546e3537d5b71144/media_kit_video/windows/utils.h#L27

**Review by alexmercerind — CHANGES_REQUESTED** [review]
Rest is good. Thanks!

File: media_kit_video/windows/media_kit_video_plugin.h (hunk 2 above)
Comment (Predidit) [reply media_kit_video/windows/media_kit_video_plugin.h]: Done

File: media_kit_video/windows/media_kit_video_plugin.cc (hunk 1 above)
Comment (alexmercerind) [inline media_kit_video/windows/media_kit_video_plugin.cc:134]:
```suggestion
          RunOnMainThread([=]() {
```
